# Setup
title: thejourneyof
tagline: me
url: https://mringive.github.io/thejourneyof-prod
paginate: 1
baseurl: "thejourneyof-prod"
permalink: /:title/

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Mathias R
  url: https://mringive.github.io
  email: mringive@gmail.com

# Custom vars
version: 3.0.0

# Excerpt
excerpt_separator: <!--more-->